import sharp from 'sharp';
import { createClient } from '@/lib/supabase-server';

export async function compositePoster(params: {
    posterUrl: string,
    subjectUrl?: string,
    logoUrl?: string,
    businessName: string,
    phone?: string,
    email?: string,
    website?: string,
    address?: string,
    primaryColor: string,
    secondaryColor?: string
}): Promise<string> {
    const { posterUrl, subjectUrl, logoUrl, businessName, phone, email, website, primaryColor } = params;

    // 1. Download the base poster image
    const posterResponse = await fetch(posterUrl);
    if (!posterResponse.ok) throw new Error("Failed to fetch poster image");
    const posterBuffer = await posterResponse.arrayBuffer();

    // The base poster is assumed to be 1080x1080 (square_hd from fal.ai)
    const baseImage = sharp(Buffer.from(posterBuffer));
    const metadata = await baseImage.metadata();
    const width = metadata.width || 1080;
    const height = metadata.height || 1080;

    const compositeOperations: sharp.OverlayOptions[] = [];

    // 1.5 Subject Placement (Center Foreground)
    if (subjectUrl) {
        try {
            const subjectResponse = await fetch(subjectUrl);
            if (subjectResponse.ok) {
                const subjectBuffer = await subjectResponse.arrayBuffer();

                // Resize the extracted food so it fits nicely in the center of the poster
                const subjectResized = await sharp(Buffer.from(subjectBuffer))
                    .resize(Math.floor(width * 0.75), Math.floor(height * 0.65), {
                        fit: 'inside',
                        background: { r: 0, g: 0, b: 0, alpha: 0 }
                    })
                    .toBuffer();

                compositeOperations.push({
                    input: subjectResized,
                    gravity: 'center',
                    blend: 'over'
                });
            }
        } catch (e) {
            console.error("Failed to add subject to composite", e);
        }
    }

    // 2. Logo Placement (Top Right)
    if (logoUrl) {
        try {
            const logoResponse = await fetch(logoUrl);
            if (logoResponse.ok) {
                const logoBuffer = await logoResponse.arrayBuffer();

                // Create a white circular background for the logo
                const circleSvg = `
                    <svg width="100" height="100">
                        <circle cx="50" cy="50" r="50" fill="white" />
                    </svg>
                `;

                const logoResized = await sharp(Buffer.from(logoBuffer))
                    .resize(80, 80, { fit: 'contain', background: { r: 255, g: 255, b: 255, alpha: 0 } })
                    .toBuffer();

                // Create a container with drop shadow (simplified using basic sharp operations)
                // For simplicity, we just put the white circle and logo on top
                const logoContainer = await sharp(Buffer.from(circleSvg))
                    .composite([{ input: logoResized, gravity: 'center' }])
                    .png()
                    .toBuffer();

                compositeOperations.push({
                    input: logoContainer,
                    top: 20,
                    left: width - 120, // 100px circle + 20px padding right
                    blend: 'over'
                });
            }
        } catch (e) {
            console.error("Failed to add logo to composite", e);
        }
    }

    // 3. Contact Strip (Bottom)
    // Create SVG for text rendering (easiest way in sharp without custom fonts installed)
    const stripHeight = 80;
    const hexColor = primaryColor.startsWith('#') ? primaryColor : `#${primaryColor}`;
    // opacity 90% is hex e6 appended to color, but CSS rgba works better in SVG
    const opacityColor = `rgba(${parseInt(hexColor.slice(1, 3), 16) || 0}, ${parseInt(hexColor.slice(3, 5), 16) || 0}, ${parseInt(hexColor.slice(5, 7), 16) || 0}, 0.9)`;

    const contactText = [phone, email, website].filter(Boolean).join('  |  ');

    // We use SVG to draw the rectangle and text
    const stripSvg = `
        <svg width="${width}" height="${stripHeight}">
            <rect x="0" y="0" width="${width}" height="${stripHeight}" fill="${opacityColor}" />
            <text x="30" y="48" font-family="sans-serif" font-size="28" font-weight="bold" fill="white">${businessName}</text>
            <text x="${width - 30}" y="48" font-family="sans-serif" font-size="24" fill="white" text-anchor="end">${contactText}</text>
        </svg>
    `;

    // 4. Brand Watermark (Bottom Left above strip)
    const watermarkSvg = `
        <svg width="${width}" height="40">
            <text x="20" y="25" font-family="sans-serif" font-size="16" fill="white" opacity="0.3">Generated by PostChef</text>
        </svg>
    `;

    compositeOperations.push({
        input: Buffer.from(stripSvg),
        top: height - stripHeight,
        left: 0,
        blend: 'over'
    });

    compositeOperations.push({
        input: Buffer.from(watermarkSvg),
        top: height - stripHeight - 40,
        left: 0,
        blend: 'over'
    });

    // 5. Final Composite
    const finalBuffer = await baseImage
        .composite(compositeOperations)
        .png()
        .toBuffer();

    // 6. Upload to Supabase Storage
    const supabase = createClient();
    const fileName = `composite_${Date.now()}_${Math.random().toString(36).substring(7)}.png`;

    const { data: uploadData, error: uploadError } = await supabase
        .storage
        .from('posters')
        .upload(fileName, finalBuffer, {
            contentType: 'image/png',
            cacheControl: '3600',
            upsert: false
        });

    if (uploadError) {
        console.error("Supabase Storage Upload Error:", uploadError);
        throw new Error("Failed to upload composited poster to storage"); // Fallback logic could return a default, but best to throw
    }

    // Get public URL
    const { data: publicUrlData } = supabase.storage.from('posters').getPublicUrl(fileName);
    return publicUrlData.publicUrl;
}
